spring:
  datasource:
    write:
      jdbc-url: ${SPRING_DATASOURCE_URL}?serverTimezone=Asia/Seoul
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      minimum-idle: 5
      maximum-pool-size: 5
      connection-test-query: SELECT 1 FROM dual
      connection-timeout: 5000
      validation-timeout: 5000
    read:
      jdbc-url: ${SPRING_DATASOURCE_URL}?serverTimezone=Asia/Seoul
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      minimum-idle: 5
      maximum-pool-size: 5
      connection-test-query: SELECT 1 FROM dual
      connection-timeout: 5000
      validation-timeout: 5000